### ISSUE TITLE
Uncaught ReferenceError: CodeMirror is not defined

### ISSUE THREAD

**Issue by raha1923** [advanced-rest-client/api-request-panel#1]
I'm trying to use it in my polymer project. I tried to use the sample way to use(the way you have mentioned in npm package markdown) but the following error happened:

```
Uncaught ReferenceError: CodeMirror is not defined
    at lint.js:7
    at lint.js:8
```

--------------

polymer: v3.0.0
@api-components/api-request-panel: v3.0.0-preview.4

**Comment by jarrodek** [comment]
Hi, see the list of [breaking changes](https://github.com/advanced-rest-client/api-request-panel#breaking-changes-in-v3) in the readme file. Code mirror has to be included before the component.
I am releasing stable 3.0.0 version today which have some improvements here.
